name: Build & Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Docker build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            driphire/slack-notify-action
            ghcr.io/${{ github.repository }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: driphire
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: driphire
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
